# Do not modify this header—generated by nixos-generate-config.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  #####################################################################
  #  Filesystem support
  #####################################################################
  boot.supportedFilesystems = [ "ntfs" ];

  #####################################################################
  #  NTFS drives (kernel ntfs3)
  #####################################################################
  
  # -- 1 TB SSD “Games” ----------------------------------------------
  fileSystems."/mnt/Games" = {
    device  = "/dev/disk/by-uuid/42ACD2E1ACD2CE93";   # /dev/sdc1
    fsType  = "ntfs";
    options = [ "uid=1000" "gid=100" "windows_names" "big_writes" "fmask=0000" "dmask=0000"];
  };

  # -- 8 TB HDD “I Was Here” -----------------------------------------
  fileSystems."/mnt/8TBDrive" = {
    device  = "/dev/disk/by-uuid/F272D58C72D55647";   # /dev/sdd1
    fsType  = "ntfs";
    options = [ "uid=1000" "gid=100" "windows_names" "big_writes" "fmask=0000" "dmask=0000"];
  };

  fileSystems."/mnt/LinuxGames" = {
    device  = "/dev/disk/by-uuid/4590010d-17ac-4e5d-a1ca-4e03b0777221";
    fsType  = "ext4";
    options = [ "noatime" ];
  };

  # # -- 2 TB HDD -------------------------------------------------------
  # #   sudo mkfs.ext4 -L Data2TB /dev/sdb1
  # fileSystems."/mnt/Data2TB" = {
  #   device  = "/dev/disk/by-label/Data2TB";           # /dev/sdb1
  #   fsType  = "ext4";
  #   options = [ "noatime" ];
  # };
}
