# Autogenerated by nixos-generate-config – edit in /etc/nixos/configuration.nix
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  networking.hostName = "shitbox";

  networking.networkmanager = {
    enable  = true;
    dns     = "systemd-resolved";
    plugins = with pkgs; [ networkmanager-openvpn ];   # WG built-in
  };

  services.resolved.enable = true;
  services.resolved.dnssec = "false";

  networking.wireguard.enable = true;
  security.polkit.enable      = true;

  ##################################################################
  #  Firewall: keep it ON, but switch to iptables so it plays nice
  ##################################################################
  networking.firewall.enable = true;          # firewall stays
  networking.nftables.enable = false;  # ← use iptables backend

  # Proton0 tunnel is trusted for return traffic (optional but tidy)
  networking.firewall.trustedInterfaces = [ "proton0" ];

  environment.systemPackages = with pkgs; [
    protonvpn-gui  protonvpn-cli
    openvpn  wireguard-tools
    iptables            # Proton & firewall share this backend
  ];
}