# Do not modify this header—generated by nixos-generate-config.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Overlay for PacketTracer
  nixpkgs.overlays = [ (import ./overlays/packettracer.nix) ];

  # Enable Firefox.
  programs.firefox.enable = true;

  # Allow unfree packages.
  nixpkgs.config.allowUnfree = true;
  services.flatpak.enable = true;

  # System-wide packages.
  environment.systemPackages = with pkgs; [
    vim htop wget git neofetch btop qbittorrent mpv
    google-chrome discord thunderbird
    ranger nautilus util-linux
    peek nix-output-monitor ciscoPacketTracer8
    vscode.fhs gedit
    caprine # Facebook Messenger Desktop App 

    # Discord wrapper (PipeWire capture + NVENC)
    (writeShellScriptBin "discord-hw" ''
      exec env \
        DISCORD_USE_PIPEWIRE=1 \
        LIBVA_DRIVER_NAME=nvidia \
        GTK_USE_PORTAL=1 \
        ${pkgs.discord}/bin/discord \
        --enable-features=VaapiVideoEncoder,VaapiVideoDecoder \
        --use-gl=desktop "$@"
    '')
  ];
}
