# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  environment.shellAliases = {
    build-nix = "sudo bash /etc/nixos/scripts/build-nix.sh";
    pkgsearch = "sudo bash /etc/nixos/scripts/pkgsearch.sh";
    pkginstall = "sudo bash /etc/nixos/scripts/pkginstall.sh";
    blackscreen = "bash /etc/nixos/scripts/blackscreen.sh";
    nixopen = "code /home/flacko/.config/nix-config";
    pkgedit = "code /home/flacko/.config/nix-config/packages.nix";
  };
}
