# Do not modify this header—generated by nixos-generate-config.
{ config, lib, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    discord google-chrome thunderbird vivaldi caprine parsec-bin filezilla
    mpv libplacebo peek guvcview pinta dia
    libreoffice-still qalculate-qt joplin-desktop baobab
    git neovim vscode.fhs gedit nix-output-monitor nh
    wget neofetch btop htop ranger util-linux usbutils
    wayland-utils weston
    qbittorrent nautilus prismlauncher pkgs.r2modman
  
    (pkgs.makeDesktopItem {
      name = "blackscreen";
      desktopName = "BlackScreen";
      icon = "view-refresh";
      exec = "/etc/nixos/Scripts/blackscreen.sh";
      terminal = true;
    })
  ];

  nixpkgs.config.allowUnfree = true;
  programs.firefox.enable = true;
  services.flatpak.enable = true;

  services.sunshine = {
    enable = true;
    autoStart = true;
    capSysAdmin = true;  # fixes the KMS capture CAP_SYS_ADMIN error on Wayland
    openFirewall = true;
  };
  
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
    pinentryPackage = pkgs.pinentry-curses;
  };
  
programs.nix-ld = {
  enable = true;
  libraries = with pkgs; [
    gtk3 glib gdk-pixbuf pango cairo atk at-spi2-core gsettings-desktop-schemas
    libxkbcommon libglvnd mesa libdrm
    xorg.libX11 xorg.libXext xorg.libXfixes xorg.libXcomposite xorg.libXcursor
    xorg.libXi xorg.libXrandr xorg.libXrender xorg.libXdamage xorg.libxcb xorg.libxshmfence
    nss nspr alsa-lib cups zlib libuuid expat fontconfig freetype stdenv.cc.cc.lib
  ];
};

  nixpkgs.overlays = [
    (final: prev: {
      layer-shell-qt = final.kdePackages.layer-shell-qt;
      libsForQt5 = prev.libsForQt5 // {
        layer-shell-qt = final.kdePackages.layer-shell-qt;
      };
    })
  ];
  
}