# Do not modify this header—generated by nixos-generate-config.
{ config, lib, pkgs, ... }:

{
  nixpkgs.config.allowUnfree = true;

  programs.firefox.enable = true;
  services.flatpak.enable = true;

  environment.systemPackages = with pkgs; [
    wget git neofetch btop qbittorrent mpv
    google-chrome vesktop thunderbird libreoffice-still
    ranger util-linux usbutils htop
    peek nix-output-monitor neovim
    vscode.fhs gedit git qalculate-qt caprine
    nh # Nix Helper
    wayland-utils weston 
    filezilla
    dia
    pkgs.r2modman
    # mattermost-desktop
    # gnupg pinentry
    prismlauncher
  ];
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
    pinentryPackage = pkgs.pinentry-curses;
  };

  nixpkgs.overlays = [
    (final: prev: {
      layer-shell-qt = final.kdePackages.layer-shell-qt;
      libsForQt5 = prev.libsForQt5 // {
        layer-shell-qt = final.kdePackages.layer-shell-qt;
      };
    })
  ];
  
services.teamviewer.enable = true;
}