# Do not modify this header—generated by nixos-generate-config.
{ config, lib, pkgs, ... }:

{
  nixpkgs.config.allowUnfree = true;

  programs.firefox.enable = true;
  services.flatpak.enable = true;

  environment.systemPackages = with pkgs; [
    #vesktop
    discord
    wget git neofetch btop qbittorrent mpv libplacebo
    google-chrome thunderbird libreoffice-still
    ranger util-linux usbutils htop
    peek nix-output-monitor neovim
    vscode.fhs gedit qalculate-qt caprine
    nh # Nix Helper
    wayland-utils weston 
    filezilla
    dia
    pkgs.r2modman
    # mattermost-desktop
    # gnupg pinentry
    prismlauncher
    guvcview
    nautilus
  ];
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
    pinentryPackage = pkgs.pinentry-curses;
  };
programs.nix-ld = {
  enable = true;
  libraries = with pkgs; [
    gtk3 glib gdk-pixbuf pango cairo atk at-spi2-core gsettings-desktop-schemas
    libxkbcommon libglvnd mesa libdrm
    xorg.libX11 xorg.libXext xorg.libXfixes xorg.libXcomposite xorg.libXcursor
    xorg.libXi xorg.libXrandr xorg.libXrender xorg.libXdamage xorg.libxcb xorg.libxshmfence
    nss nspr alsa-lib cups zlib libuuid expat fontconfig freetype stdenv.cc.cc.lib
  ];
};

  nixpkgs.overlays = [
    (final: prev: {
      layer-shell-qt = final.kdePackages.layer-shell-qt;
      libsForQt5 = prev.libsForQt5 // {
        layer-shell-qt = final.kdePackages.layer-shell-qt;
      };
    })
  ];
  
services.teamviewer.enable = true;
}